name: Nightly Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-nightly:
    strategy:
      matrix:
        python-version: [3.7-dev, 3.8-dev, 3.9-dev, 3.10-dev]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nightly Python
        uses: deadsnakes/action@v2.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}/lib/*/site-packages/*
            ${{ env.pythonLocation }}/bin/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip install -U wheel setuptools coveralls
          pip install -Ur requirements.txt
          python setup.py develop
      - name: Run tests
        run: |
          coverage run --source=thefuck,tests -m py.test -v --capture=sys tests